neuronsimulator/nrn-modeldb-ci

modeldb/modelrun.py
Fixes warnings like
```
0 ./x86_64/special: can't open 
```
=> Do not pass empty string when using HOC.

modeldb/modeldb-run.yaml, modeldb/report.py
Closes #17. This is meant more as a template for ongoing work; I make no claim that this is in any way comprehensive.
=> model-specific output fudging + generic patterns.

.github/workflows/nrn-modeldb-ci.yaml, modeldb/modeldb-run.yaml, modeldb/modeldb.py
- Unzip the compressed data file in model 244262
- Update cache key to include the month => cache is never more than a month out of date.
- Support a `github` key in the YAML configuration that overwrites the ModelDB copy of a model with the GitHub copy.
=> Support fetching models from GitHub. Make cache expire.

modeldb/modeldb-run.yaml
=> make sed cross-platform

modeldb/modelrun.py
Now the output includes a representation of the byte sequence that could not be decoded, which aids debugging.
=> utf-8: more debug output when decoding fails

modeldb/commands.py, modeldb/modeldb-run.yaml, modeldb/modeldb.py, modeldb/modelrun.py
- fix `--virtual` on macOS
- support fetching models from forked repositories on GitHub
- disable build parallelism internal to `nrnivmodl`
- do some more model curation
=> macOS fixes, model curation, etc.

.github/workflows/nrn-modeldb-ci.yaml, modeldb/commands.py, modeldb/report.py
=> Report meaningful pipeline status

.github/workflows/nrn-modeldb-ci.yaml, modeldb/commands.py, modeldb/modeldb-run.yaml, modeldb/modelrun.py, modeldb/report.py
Many of the diffs are due to error messages that are, in essence, the same on both sides of the comparison.
Some error message formatting has changed since NEURON 8.2.2, so "the same error" can still result in a diff.
This is an effort to avoid the problem by fixing the errors, with obvious benefits.
To be merged first + `github:` keys removed from YAML in this PR:
=> Clean up differences between neuron and neuron-nightly

modeldb/modeldb-run.yaml
Most likely this was broken when I cleaned up https://github.com/neuronsimulator/nrn-modeldb-ci/pull/67 in 4e6e5ce9f327ffed7f14ff36f07926e3316c060c and stopped appending 7 lines to `driver.hoc`. 
https://github.com/neuronsimulator/nrn/actions/runs/4859158250 fails because
```
in %model_dir%/driver.hoc near line 37
```
fails to be removed from the diff.
MODELS_TO_RUN=33975
=> Remove hardcoded line number

modeldb/commands.py, modeldb/modeldb-run.yaml, modeldb/modelrun.py, modeldb/report.py
- Previously error code 1 was counted as success.
- When `gout` diffs were large, making the HTML report could be very slow. Add a timeout.
- Start to address more issues in new and existing models.
=> Improve error and diff handling

modeldb/report.py
The variable `diff_out` is supposed to be a string but it accidentally got split into a list of lines and it's never joined back into a string. This PR ensures that `diff_out` is always converted back into a string.
=> fix bug in report.py

.github/workflows/nrn-modeldb-ci.yaml, README.md, modeldb/config.py, modeldb/modeldb.py
- Stop fetching from the Yale website.
- Improve cache management
- Always make two bulk API calls to get **all** NEURON model IDs and their last-modification timestamps.
- Use those timestamps to decide whether the given (or all) models need to be re-downloaded.
Closes https://github.com/neuronsimulator/nrn-modeldb-ci/issues/82.
=> Fetch models from https://modeldb.science/

modeldb/modeldb-run.yaml, modeldb/modeldb.py, modeldb/modelrun.py
Should avoid having to explicitly set model_dir for models with a simple directory structure.
Unfortunately this exposes various models with `.mod` files that do not compile, which were previously missed because there was no `model_dir` setting **and** the `.mod` files were not at the top level.
The following 30 models are now skipped, because their `.mod` files do not compile: 7907 125385 144579 147141 154096 155735 155796 182134 183014 183718 184497 229585 230861 237469 239421 240116 246546 256311 261460 265523 266732 266799 266806 266864 267146 267189 267511 267587 267595 267646.
Additionally new model 241169 is not executed, because it makes invalid assumptions that break with `neuron-nightly`.
=> Improve .mod search strategy

modeldb/commands.py, modeldb/modeldb-run.yaml
- Fix bug where >1 gout diff was required for the status code to be non-zero
- New ModelDB entries where automatic `.mod` search did not work: 267599, 2014814
- 116094: do not run so much to avoid gout diff between 8.2.2 and neuron-nightly
- Probably before https://github.com/neuronsimulator/nrn-modeldb-ci/pull/85 this was not seen because the .mod files were not compiled.
=> gout: report errors; 267599, 2014814: model dirs

modeldb/modeldb-run.yaml
In NEURON 8.2.3, there are warnings of the form:
```plaintext
%neuron-executable%: Assignment to modern physical constant FARADAY
in batch_.hoc near line 90
FARADAY = 96520.        /* Hoc default = 96484.56 */
^
```
which do not appear to be present in NEURON 9. Warnings of this kind are present in the following models:
- 105507
- 106891
- 116838
- 116862
- 12631
- 136095
- 136310
- 138379
- 144538
- 145672
Note that model 144538 has some additional issues which should be resolved (see [this run](https://github.com/neuronsimulator/nrn-modeldb-ci/actions/runs/7612231849)).
=> Remove warnings about dynamic units

modeldb/modeldb-run.yaml
The model https://github.com/ModelDBRepository/144538 is failing in the CI using NEURON 9 with the following error:
```plaintext
%neuron-executable%: syntax error
in arm.hoc near line 163
nqDP.append(1,xo.id,DP,xo.zloc,MTYP.o(xo.zloc).s,shminmlen,shmaxmlen)
^
xopen("arm.hoc")
execute1("{xopen("ar...")
load_file("arm.hoc")
%neuron-executable%: hoc_Load_file arm.hoc
in arm.hoc near line 33
^
load_file("arm.hoc")
hoc_run1: caught exception: hoc_execerror: hoc_Load_file arm.hoc
```
It's not really clear what the source of the problem is, and as the model is quite old, it's probably better to fix it later, but exclude it from the CI in the meantime.
=> Exclude failing model from running in CI

modeldb/modeldb-run.yaml
Model 2014998 needs some minor changes in order to be compatible with NEURON 9, and for now we set the source to `github: default` which has them.
Verification: https://github.com/neuronsimulator/nrn-modeldb-ci/actions/runs/7615231720
=> Set different source for 2014998

modeldb/modeldb-run.yaml
The call to `<Vector>.plot` in `Fig3A.hoc` outputs `Vector[<int>]` to stdout which does not seem to have an impact on the results.
Verification: https://github.com/neuronsimulator/nrn-modeldb-ci/actions/runs/7626068663
=> Filter output from 180373

modeldb/modeldb-run.yaml
A recent [model update](https://github.com/ModelDBRepository/266498/commit/f7d1fab5099e43886666c3e0dffc7be3d85a94cf) broke the CI. Not really sure why it was working in the first place though since it had multiple mod directories even before the update.
MODELS_TO_RUN=266498
=> Fix multiple mod file dirs in 266498

setup.py
Part of the NumPy 2 workarounds.
MODELS_TO_RUN=187604
=> Explictly specify numpy version

.github/workflows/nrn-modeldb-ci.yaml
Due to stricter version parsing (introduced in [this commit](https://github.com/pypa/pip/commit/47a8480065d4eac252edb3673cfaecccb7dbf3c2)), newer versions of pip fail to uninstall versions of NEURON like `9.0a-294-g21ea378fd`.
Should fix https://github.com/neuronsimulator/nrn/issues/2969
=> Pin pip to version <=24.0

modeldb/modeldb-run.yaml
Skip these models for now to keep the CI green:
- 2014832
- 2017405
=> Skip models that do not compile

modeldb/modeldb-run.yaml
- 2016138 does not compile on NEURON 9.0
=> Skip model 2016138

.github/workflows/nrn-modeldb-ci.yaml
=> Fix issue with `pip install --find-links`

modeldb/modeldb-run.yaml
MODELS_TO_RUN=138379 229276 146949
Links to PRs:
- https://github.com/ModelDBRepository/18502/pull/1
- https://github.com/ModelDBRepository/138379/pull/4
- https://github.com/ModelDBRepository/229276/pull/4
- https://github.com/ModelDBRepository/146949/pull/5
Note that the CI fails, but this is because 8.2.6 on PyPI doesn't have the `TABLE` fix; if we apply the fix, it passes: https://github.com/neuronsimulator/nrn-modeldb-ci/actions/runs/11821925920/job/32937782329
=> Fixes for RNG, part 3
