.github/workflows/nrn-modeldb-ci.yaml

* manual workflow: specify v1 and v2 and list of models to run
* nightly runs: last release vs last nightly
* also run on `push`, sort of integration CI

GitHub Actions: nrn-modeldb-ci

---

.github/workflows/nrn-modeldb-ci.yaml
modeldb/report.py

gout may be missing from one of the paths

---

.github/workflows/nrn-modeldb-ci.yaml
modeldb/report.py

(after discussion on slack) 
Curated locally with:
```bash
diffreports2html 8.0.2.json 8.0a-771-g6a063080.json
```
from :
to:

diffreports2html: curate `nrniv:` <-> `special:` messages

---

.github/workflows/nrn-modeldb-ci.yaml
README.md
modeldb/commands.py
requirements.txt

* add --virtual option to launch everything in a virtual display
* back-end required (Xvfb)

runmodels + pyvirtualdisplay

---

LICENSE.txt
README.md

add license and funding

---

modeldb/report.py

diffreports2html: avoid pointless gout comparisons

---

.github/workflows/nrn-modeldb-ci.yaml
README.md
modeldb/commands.py
modeldb/modelrun.py

* consequent runs can alter some models
* check if WorkingDirectory is non empty
* propose --clean option

add `--clean` option for `runmodels`

---

modeldb/report.py

* make model name searchable
* be in line with git-like diff for gout
@nrnhines we were discussing about this UX improvement. We can now  have:

diffreports2html: `nrn_run` shall show the directory

---

modeldb/commands.py
modeldb/modelrun.py

* compile and link only
Closes #31 
Note I have only done some sanity checking (didn't run all models)

`runmodels`: add `--norun` option

---

README.md
modeldb/commands.py
modeldb/modelrun.py

Add `--inplace`  option for `runmodels`

---

modeldb/modelrun.py

architecture: use platform.machine()

---

.github/workflows/nrn-modeldb-ci.yaml
modeldb/commands.py

(hopefully) closes #26 
I've been experimenting with several Xvfb options and as well with `manage_global_env=False` in pyvirtualdisplay. So far this combination hasn't yielded any DISPLAY issues.

mitigate "can't open DISPLAY"

---

.github/workflows/nrn-modeldb-ci.yaml
modeldb/modelrun.py

Also have a break-down for runtime: 
* model run
* nrnivmodl
Temporarily drop timeout in CI

Improvement: break-down runtimes

---

modeldb/report.py

`nrn_run` use `unified_diff` from difflib instead of `make_table`

---

.github/workflows/nrn-modeldb-ci.yaml
modeldb/modeldb-run.yaml

curate 244922, 143719

---

modeldb/modeldb-run.yaml

Verification: https://github.com/neuronsimulator/nrn-modeldb-ci/actions/runs/7587115676

Fix multiple mod file dirs in 267694

---

modeldb/modeldb-run.yaml

Verification: https://github.com/neuronsimulator/nrn-modeldb-ci/actions/runs/7608251605

Fix multiple mod file dirs in 267768

---

modeldb/modeldb-run.yaml

The change in random for 150245 changed the number of spikes which requires a change in a pattern replace line in modeldb-run.yaml

fix 150245 pattern replace

---

modeldb/modeldb-run.yaml

Fix regex pattern for model 146030

---

modeldb/modeldb-run.yaml

MODELS_TO_RUN=2016658
Specify dir for the model.

Fix model 2016658

---

modeldb/modeldb-run.yaml

Pick a dir for 2016662

---

modeldb/modeldb-run.yaml

(**Note**: we run a random model here that passes the CI so I don't need to override the "required" workflows manually).
MODELS_TO_RUN=138379
Links:
- https://github.com/ModelDBRepository/82784/pull/1
- https://github.com/ModelDBRepository/138379/pull/4
- https://github.com/ModelDBRepository/150245/pull/5 (RNG fix gets rid of errors, but the outputs are slightly different)
Actually passes the CI with `TABLE` fix applied to 8.2.6, see: https://github.com/neuronsimulator/nrn-modeldb-ci/actions/runs/11853083212/job/33032497897

Fixes for RNG, part 4
